# Generated by Django 3.2.5 on 2021-07-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pose',
            name='name',
            field=models.CharField(default='Vrikshasana', max_length=64),
            preserve_default=False,
        ),
    ]
