# Generated by Django 3.2.5 on 2021-07-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pose',
            name='number',
        ),
        migrations.AlterField(
            model_name='pose',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
