# Generated by Django 3.2.5 on 2021-08-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_choice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pose',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
